package com.mrcd.xrouter;

import com.mrcd.xrouter.core.IntentInterceptor;
import com.mrcd.xrouter.routers.AdapterPreviewActivityRouter;
import com.mrcd.xrouter.routers.BottomTabActivityRouter;
import com.mrcd.xrouter.routers.HttpsDemoActivityRouter;
import com.mrcd.xrouter.routers.PermissionActivityRouter;

/**
 * Generated by XRouter, please do not modify
 */
public final class XRouter {
  private static XRouter INSTANCE = new XRouter();

  private IntentInterceptor mGlobalInterceptor;

  private XRouter() {
  }

  public static XRouter getInstance() {
    return INSTANCE;
  }

  public void setGlobalInterceptor(IntentInterceptor interceptor) {
    mGlobalInterceptor = interceptor;
  }

  public BottomTabActivityRouter bottomTabActivity() {
    return new BottomTabActivityRouter().setInterceptor(mGlobalInterceptor);
  }

  public HttpsDemoActivityRouter httpsDemoActivity() {
    return new HttpsDemoActivityRouter().setInterceptor(mGlobalInterceptor);
  }

  public AdapterPreviewActivityRouter adapterPreviewActivity() {
    return new AdapterPreviewActivityRouter().setInterceptor(mGlobalInterceptor);
  }

  public PermissionActivityRouter permissionActivity() {
    return new PermissionActivityRouter().setInterceptor(mGlobalInterceptor);
  }
}
